
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radixappdeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: radixlabel
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  template:
    metadata:
      name: radixpod
      labels:
        app: radixlabel
    spec:
      containers:
      - name: radixcontainer
        image: radixacr.azurecr.io/radix:${{ env.PR_ID }}
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: radixservice
spec:
  type: LoadBalancer
  selector:
    app: radixlabel
  ports:
  - port: 80
