apiVersion: apps/v1
kind: Deployment
metadata:
  name: radix_app_deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: radix_label
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  template:
    metadata:
      name: radix_pod
      labels:
        app: radix_label
    spec:
      containers:
      - name: radix_container
        image: ""
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: radix_service
spec:
  type: NodePort
  selector:
    app: radix_label
  ports:
  - port: 80
