name: Build a Docker image and Push it to ACR.

on:
  push:
    paths:
    - 'Test/index.html'
  pull_request:
    paths: 
    - 'Test/index.html'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: radixacr.azurecr.io
          username: RadixACR
          password: Q0qTKyA6jeURTF5/Q2tjiIWM2PXdHZdR

      - run: |
          docker build . -t radixacr.azurecr.io/build1:${{ github.sha }}
          docker push radixacr.azurecr.io/build1:${{ github.sha }}
