name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  PR_ID: ${{ github.event.pull_request.id}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: radixacr.azurecr.io
          username: RadixACR
          password: Q0qTKyA6jeURTF5/Q2tjiIWM2PXdHZdR
      - name: view the PR number
        run: |
          echo "PR number = ${{ github.event.pull_request.number }}"
          echo "PR number = ${{ env.PR_NUMBER }}"
          echo "PR ID = ${{ github.event.pull_request.id }}"
          echo "PR ID = ${{ env.PR_ID }}"
      - run: |
#          docker build . -t radixacr.azurecr.io/build2:${{ github.sha }}
#          docker push radixacr.azurecr.io/build2:${{ github.sha }}
      
      - name: Az CLI login
        uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIAL }}
       
          
        
#      - name: Get K8s context
        uses: azure/aks-set-context@v2.0
        with:
          resource-group: Radix_RG
          cluster-name: RadixAKS
          
    #  - name: Create K8s secret for pulling image from ACR
 #       uses: Azure/k8s-create-secret@v1.1
        with:
          container-registry-url: radixacr.azurecr.io
          container-registry-username: RadixACR
          container-registry-password: Q0qTKyA6jeURTF5/Q2tjiIWM2PXdHZdR
          secret-name: radix
          
#      - name: Deploys application
 #       uses: Azure/k8s-deploy@v3.0
        with:
          namespace: radixdeploymentpr1
          action: deploy
          manifests: k8.yml
          images: |
            radixacr.azurecr.io/build2:${{ github.sha }}
          imagepullsecrets: |
            radix
          
 
