name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: radixacr.azurecr.io
          username: RadixACR
          password: Q0qTKyA6jeURTF5/Q2tjiIWM2PXdHZdR

   
      - name: view the PR number
        run: |
          echo "PR number = ${{ github.event.pull_request.number }}"
          echo "PR number = ${{ env.PR_NUMBER }}"   
