name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: radixacr.azurecr.io
          username: RadixACR
          password: Q0qTKyA6jeURTF5/Q2tjiIWM2PXdHZdR

      - run: |
          docker build . -t radixacr.azurecr.io/build1:${{ github.sha }}
          docker push radixacr.azurecr.io/build1:${{ github.sha }}
      
      - name: Azure login
        uses: azure/login@v1.4.3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
      - name: Get K8s context
        uses: azure/aks-set-context@v2.0
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          
      - name: Create K8s secret for pulling image from ACR
        uses: Azure/k8s-create-secret@v1.1
        with:
          container-registry-url: radixacr.azurecr.io
          container-registry-username: RadixACR
          container-registry-password: Q0qTKyA6jeURTF5/Q2tjiIWM2PXdHZdR
          secret-name: ${{ env.IMAGE_PULL_SECRET_NAME }}
          
      - name: Deploys application
        uses: Azure/k8s-deploy@v3.0
        with:
          action: deploy
          manifests: ${{ env.DEPLOYMENT_MANIFEST_PATH }}
          images: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }}
          imagepullsecrets: |
            ${{ env.IMAGE_PULL_SECRET_NAME }}
          
 
